config/routes.rb
Rails.application.routes.draw do
  root 'users#index'

  resources :users do
    resources :ledgers
  end
  post '/verify', to: 'users#verify'

end

app/models/ledger.rb
class Ledger < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :ledgers
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/ledgers_controller.rb
class LedgersController < ApplicationController
  def index
    @user = User.find(params[:user_id])
    @ledgers = @user.ledgers
  end

  def new
    @ledger = Ledger.new
  end

  def create
    params.permit!
    @user = User.where('id = ?', params[:user_id])
    @user.first.ledgers.create(params[:ledger])
    redirect_to user_ledgers_path
  end

  def show
    user_id = params[:user_id]
    @ledger = Ledger.find(params[:id])
    @ledgers = Ledger.where('user_id = ? AND name = ?', user_id, @ledger.name)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @user = User.new
  end

  def new
    @user = User.new
  end

  def create
    name = params[:user][:name]
    email = params[:user][:email]
    password = params[:user][:password]
    @user = User.create(name: name, email: email, password: password)
    redirect_to user_path(id: @user.id)
  end

  def verify
    @user = User.where('email = ? AND password = ?', params[:user][:email], params[:user][:password])
    if @user != []
      redirect_to user_path(id: @user.first.id)
    else
      flash[:notice] = "Login Fail"
      redirect_to root_path, flash: { notice: "Login Fail"}
    end      
  end

  def show
    redirect_to user_ledgers_path(params[:id])
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ledgers_helper.rb
module LedgersHelper
  def filter_result(attr_name)
    return attr_name != "user_id" && attr_name != "created_at" && attr_name != "updated_at" && attr_name != "id"
  end

  def get_date(ledger)
    day = ledger.created_at.day
    month = ledger.created_at.month
    year = ledger.created_at.year
    "#{month}/#{day}/#{year}"
  end

  def time_ago(created_at)
    sec = Time.now - created_at
    from_time = Time.now - sec
    return time_ago_in_words(from_time)
  end

end

app/helpers/workouts_helper.rb
module WorkoutsHelper
  def filter_result(attr_name)
    return attr_name != "user_id" && attr_name != "created_at" && attr_name != "updated_at" && attr_name != "name" && attr_name != "id"
  end

  def get_date(workout)
    day = workout.created_at.day
    month = workout.created_at.month
    year = workout.created_at.year
    "#{month}/#{day}/#{year}"
  end
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Ledger App
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
    <link href='http://fonts.googleapis.com/css?family=Signika' rel='stylesheet' type='text/css'>
    = stylesheet_link_tag 'css/application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
    %script{:src => "http://code.highcharts.com/modules/exporting.js"}
    %script{:src => "http://code.jquery.com/jquery-1.11.1.min.js"}
    %script{:src => "http://code.highcharts.com/highcharts.js"}
  %body
    = yield

app/views/ledgers/_form.html.haml
.ledger_form
  = link_to "Back", user_ledgers_path

  = form_for @ledger, :url => user_ledgers_path, :html => { :method => :post } do |f| 

    = f.text_field :name, placeholder: "Exercise", class: "input-field"
    = f.text_field :set, placeholder: "Set", class: "input-field"
    = f.text_field :reps, placeholder: "Reps", class: "input-field"
    = f.text_field :weight, placeholder: "Weight", class: "input-field"
    = f.text_field :time, placeholder: "Time", class: "input-field"
    = f.text_field :distance, placeholder: "Distance", class: "input-field"
    = f.text_field :feel, placeholder: "Feel", class: "input-field"

    = f.submit "Log"

app/views/ledgers/index.html.haml
.container
  .header
    .title-header
      Welcome, #{@user.name.capitalize}!
    #menu-button.fa.fa-bars
  .ledger-list
    = link_to content_tag(:i, nil, class: "fa fa-plus"), new_user_ledger_path



  .ledgers
    - @ledgers.reverse_each do |ledger|
      .item
        = ledger.item
        $#{ledger.price}0
      .note  
        = ledger.note
      .date
        = time_ago(ledger.created_at)

  %table{class: "ledger-table"}
    %tbody
      %tr{class: "top_row"}
        %td
          Date
        %td
          Item
        %td
          Price
        %td
          Note
        %td
          Payment Type
        / - @ledgers.first.attributes.each do |attr_name, value|
      - @ledgers.each do |ledger|
        %tr{class: "table-content"}
          %td= get_date(ledger)
          %td= ledger.item
          %td= ledger.price
          %td= ledger.note
          %td= ledger.payment_type

app/views/ledgers/new.html.haml
= render partial: "form"

app/views/ledgers/show.html.haml
.ledger-container
  .header
    .title-header
      #{@ledgers.first.name.capitalize}
    .menu-button
      = link_to content_tag(:i,nil, class:"fa fa-reply"), user_ledgers_path(user_id: params[:user_id])
  %br
  #container{:style => "min-width: 410px; height: 300px; margin: 0 auto"}
  = render partial: "form"

  %table{class: "table_format"}
    %tr
      %td{class: "top_row"}
        Date
      - @ledgers.first.attributes.each do |attr_name, value|
        %td{class: "top_row"}
          - if value != nil
            - if filter_result(attr_name)
              = attr_name.capitalize
      - @ledgers.each do |ledger|
        %tr
          %td
            = get_date(ledger)
          - ledger.attributes.each do |attr_name, value|
            %td
              - if value != nil
                - if filter_result(attr_name)
                  = value 

app/views/users/index.html.haml
.container
  = form_for @user, url: {action: "verify"} do |f| 
    = f.text_field :email, placeholder: 'Email', class: "input-field", required: true
    = f.password_field :password, placeholder: 'Password', class: "input-field", required: true
    = f.submit "Login", class: "btn"

    = link_to "Sign Up", new_user_path, id: "signup"

%br
%br

.flash_msg
  - flash.each do |name, msg|
    = msg

app/views/users/new.html.haml
.container
  = form_for @user do |f| 

    = f.text_field :name, placeholder: 'Name', class: "input-field", required: true

    = f.text_field :email, placeholder: 'Email', class: "input-field", required: true  

    = f.password_field :password, placeholder: 'Password', class: "input-field", required: true

    = f.submit "Signup", class: "btn"

app/views/workouts/_form.html.haml
.workout_form
  = link_to "Back", user_workouts_path

  = form_for @workout, :url => user_workouts_path, :html => { :method => :post } do |f| 

    = f.text_field :name, placeholder: "Exercise", class: "input-field"
    = f.text_field :set, placeholder: "Set", class: "input-field"
    = f.text_field :reps, placeholder: "Reps", class: "input-field"
    = f.text_field :weight, placeholder: "Weight", class: "input-field"
    = f.text_field :time, placeholder: "Time", class: "input-field"
    = f.text_field :distance, placeholder: "Distance", class: "input-field"
    = f.text_field :feel, placeholder: "Feel", class: "input-field"

    = f.submit "Log"

app/views/workouts/show.html.haml
.workout-container
  .header
    .title-header
      #{@workouts.first.name.capitalize}
    .menu-button
      = link_to content_tag(:i,nil, class:"fa fa-reply"), user_workouts_path(user_id: params[:user_id])
  %br
  #container{:style => "min-width: 410px; height: 300px; margin: 0 auto"}
  = render partial: "form"

  %table{class: "table_format"}
    %tr
      %td{class: "top_row"}
        Date
      - @workouts.first.attributes.each do |attr_name, value|
        %td{class: "top_row"}
          - if value != nil
            - if filter_result(attr_name)
              = attr_name.capitalize
      - @workouts.each do |workout|
        %tr
          %td
            = get_date(workout)
          - workout.attributes.each do |attr_name, value|
            %td
              - if value != nil
                - if filter_result(attr_name)
                  = value 


:javascript
  $(document).ready(function() {
  chart;
  
  var chart = $(function () {
  $('#container').highcharts({
      title: {
          text: 'Workout Progress',
          x: -20 //center
      },
      xAxis: {

          categories: [ 
            #{
              @workouts.map {|workout| "#{get_date(workout)}"}.join(', ')
            }]
      },
      yAxis: {
          title: {
              text: 'Average reps'
          },
          plotLines: [{
              value: 0,
              width: 1,
              color: '#808080'
          }]
      },
      tooltip: {
          valueSuffix: ' reps'
      },
      legend: {
          layout: 'vertical',
          align: 'right',
          verticalAlign: 'middle',
          borderWidth: 0
      },
      series: [{
          name: "#{@workouts.first.name}",
          data: [ 
            #{
              @workouts.map {|workout| "#{workout.reps}"}.join(', ')
            }]
      }]
  });
  });
  });